[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm run install:all']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start:prod'

[variables]
NODE_ENV = 'production' 