[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
    'npm install --prefix shared',
    'npm install --prefix server',
    'npm install --prefix client'
]

[phases.build]
cmds = [
    'cd shared && npm run build',
    'cd ../server && npm run build',
    'cd ../client && npm run build'
]

[start]
cmd = 'npm run start:prod --prefix server'

[variables]
NODE_ENV = 'production' 