[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
    'npm install --prefix server',
    'npm install --prefix client'
]

[phases.build]
cmds = [
    'npm run build --prefix server',
    'npm run build --prefix client'
]

[start]
cmd = 'npm start --prefix server'

[variables]
NODE_ENV = 'production' 